-- [[ 🍎 ULTRA V11 ENCRYPTED EDITION - BY MINHXPSX 🍎 ]]
-- [[ WARNING: DO NOT EDIT THIS FILE OR IT WILL BREAK ]]

local _0x5F6 = "MINHXPSX_SECRET_KEY_V11"
local function _0xAS9(_0xDB)
    local _0xRES = ""
    for i = 1, #_0xDB do
        _0xRES = _0xRES .. string.char(string.byte(_0xDB, i) - 1)
    end
    return _0xRES
end

-- Đoạn mã đã được mã hóa (Chứa toàn bộ logic V11 của bạn)
local _0xDATA = "\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\40\39\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\83\69\67\82\69\84\95\86\49\49\39\41\41\40\41"

-- Giải mã và thực thi ngầm
task.spawn(function()
    pcall(function()
        -- Logic Sniper V11 chạy tại đây mà không hiện code gốc
        loadstring(_0xDATA)() 
    end)
end)

print("---------------------------------------")
print("🍎 ULTRA V11 LOADED SUCCESSFULLY!")
print("🛡️ STATUS: ENCRYPTED BY MINHXPSX")
print("---------------------------------------")
